### ISSUE TITLE
JIFF (Just Ilias's Free Feedback)

### ISSUE THREAD

**Issue by IliasDeros** [Yoh0xFF/jarvs-minesweeper#1]
Overall, the Windows XP style of this minesweeper gave me a great kick of nostalgia :') I had fun with it and almost beat beginner mode! 
Great attention to detail, I love the screen shake when you fail. And overall, the code is very easy to follow, mostly because of how centralized the logic is (inside `useGameController.ts` & `gameStateUpdate.ts`).

# Feedback 1: Issue with expert mode on mobile🐞 
## Bug Description
On mobile, playing expert, the left side of the board is cut off

## Expected Behavior
Being able to scroll horizontally to view the left side of the board, or scaling down to fit in the screen.

## Screenshot
![image](https://user-images.githubusercontent.com/9534435/179303697-176e5a78-d8ec-44a6-b4cd-4873dc0cae92.png)

# Feedback 2: Testing 👎 
A few tests, such as asserting the game ends when you click a mine, could run in CI and future-proof the code! 

# Feedback 3: Code 
## Splitting up Logic & UI 👍
I find interesting how you split up logic & ui code. It makes the UI components lighter and allows focusing display logic.

## Magic Numbers 👎
Some pieces of UI code have numbers which, in my opinion, make the code harder to understand. For example in `src/game-ui/controls/Tableau.tsx`, why are the limits 999 and -99? I would love to see you extract these numbers into constants.

## Hints update logic ⭐ 
The most complex part of this game has to be showing the hints, and you handled this perfectly with `steps` variable, representing each neighbor cells, and incrementing `CellTypes` for hints! 
```
export const steps = [
  [-1, -1],
  [-1, 0],
  [-1, 1],
  [0, 1],
  [1, 1],
  [1, 0],
  [1, -1],
  [0, -1],
];
```

## Duplication around setting mines 👎 
Could we extract a method for doing the following:
1. Find an available cell
2. Call `_setMine` for that cell
```
while (true) {
    const nx = generateRandomInt(rows);
    const ny = generateRandomInt(cols);

    if (_setMine(nx, ny, board)) break;
}
```

Would become:
```
function _addRandomMine(board: Board) {
    let hasAddedMine = false
    
    while (!hasAddedMine) {
        const x = generateRandomInt(rows);
        const y = generateRandomInt(cols);
        hasAddedMine = _setMine(x, y, board)
    }
}

_addRandomMine(board)
```

**Comment by Yoh0xFF** [comment]
Thank you, @IliasDeros, for the great feedback!

I addressed and fixed the following issues:
- Fixed the display issue for the small screen devices
- Replaced the magic numbers with constants
- Added `_addRandomMine` function as recommended and removed the code duplication

Unit tests require a little more work, and I will add them in a couple of weeks. I am currently busy at work.

I will keep this issue open until I add the unit tests.

**Comment by Yoh0xFF** [comment]
I added unit tests for the game logic and UI components.

I am marking this issue as resolved.
